<?php defined('SYSPATH') or die('No direct script access.');
/**
 * Pages controller. 
 *
 * @package    Zest
 * @author     Marmalade on Toast
 * @copyright  (c) 2007-2009 Marmalade on Toast
 * @license    http://kohanaphp.com/license.html
 */
class Change_status_Controller extends Zest_admin_Controller {

	public function __construct() {
		parent::__construct();
	}

	private $page_array = array();

		
	public function index($type,$id) {				
		$item = ORM::factory($type,$id[0]);
		$s = $item->status_id;
		echo $s;
		
		if ($s == 1)
			$item->status_id = 2;
		else 
			$item->status_id = 1;	

		$item->save();
	}
		
	public function __call($method, $arguments)
	{
		$this->index($method,$arguments);
		//exit;
	
		// Disable auto-rendering
		//$this->auto_render = FALSE;

		// By defining a __call method, all pages routed to this controller
		// that result in 404 errors will be handled by this method, instead of
		// being displayed as "Page Not Found" errors.
		//echo 'This text is generated by __call. If you expected the index page, you need to use: welcome/index/'.substr(Router::$current_uri, 8);
	}

} // End Welcome Controller